name: "NowSecure Scan"

on:
  workflow_dispatch:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Java
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "adopt"
          cache: "gradle"

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v3

      - name: Build application
        run: ./gradlew assembleDebug --stacktrace --no-daemon

      - name: Upload application
        uses: actions/upload-artifact@v4
        with:
          name: app
          path: ./app/build/outputs/apk/debug/app-debug.apk
          retention-days: 3

  # Scan the Android application with NowSecure.
  scan:
    runs-on: ubuntu-latest
    outputs:
      report_id: ${{ steps.upload.outputs.report_id }}
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # NOTE: ripgrep is required for line-of-code identification.
      - name: Install ripgrep
        run: sudo apt-get install -y ripgrep

      - name: Download application
        uses: actions/download-artifact@v4
        with:
          name: app
          
      - name: check for existing scan
        run: |
          APP_REF=$(curl --request POST --header 'content-type: application/json' --header "Authorization: Bearer ${{ secrets.NS_TOKEN }}" --url 'https://api.nowsecure.com/graphql' --data '{"query":"query Applications($platformTypes: [PlatformEnum!], $packageKeys: [String!], $groupRefs: [UUID!]) {\n  auto {\n    applications(platformTypes: $platformTypes, packageKeys: $packageKeys, groupRefs: $groupRefs) {\n      ref\n    }\n  }\n}","variables":{"platformTypes":"android","packageKeys":"com.klewis61.githubdemo","groupRefs":"3ee935d6-c347-4c45-967b-5c8e443392e5"}}' | jq -r '.data.auto.applications[0].ref')

          CURL_CMD="curl --request POST --header 'content-type: application/json' --header "Authorization: Bearer ${{ secrets.NS_TOKEN }}" --url 'https://api.nowsecure.com/graphql' --data '{"query":"query LatestAssessmentSummary($ref: UUID!) {\n  auto {\n    application(ref: $ref) {\n      latestAssessmentSummary {\n        status\n      }\n    }\n  }\n}","variables":{"ref":"$APP_REF"}}'"


          STATUS=$(curl --request POST --header 'content-type: application/json' --header "Authorization: Bearer ${{ secrets.NS_TOKEN }}" --url 'https://api.nowsecure.com/graphql' --data '{"query":"query LatestAssessmentSummary($ref: UUID!) {\n  auto {\n    application(ref: $ref) {\n      latestAssessmentSummary {\n        status\n      }\n    }\n  }\n}","variables":{"ref":"$APP_REF"}}'")

          echo "Status = $STATUS"
        
      - id: upload
        name: NowSecure upload app
        uses: nowsecure/nowsecure-action/upload-app@v4
        with:
          platform_token: ${{ secrets.NS_TOKEN }}
          app_file: app-debug.apk
          # TODO: Replace the Group ID.
          group_id: "3ee935d6-c347-4c45-967b-5c8e443392e5"

  # Pulls the NowSecure report, converts it to SARIF and uploads it.
  process:
    if: ${{ needs.scan.outputs.report_id }}
    runs-on: ubuntu-latest
    permissions:
      # required for all workflows
      security-events: write
      # only required for workflows in private repositories
      actions: read
      contents: read
    environment:
      name: nowsecure-env
    needs: scan
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: NowSecure download report
        uses: nowsecure/nowsecure-action/convert-sarif@v4
        timeout-minutes: 120
        with:
          report_id: ${{ needs.scan.outputs.report_id }}
          platform_token: ${{ secrets.NS_TOKEN }}
          # TODO: Replace the Group ID.
          group_id: "3ee935d6-c347-4c45-967b-5c8e443392e5"

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: NowSecure.sarif

      - name: Upload SARIF to artifacts
        uses: actions/upload-artifact@v4
        with:
          name: NowSecure.sarif
          path: ./NowSecure.sarif
